### ISSUE TITLE
生成静态站抛异常

### ISSUE THREAD

**Issue by sandianyiyuan** [lixuetaoleo/Personal-Blog-prototype#3]
生成静态文件时抛异常，怎么解决呀  
```
$ hexo g
INFO  Validating config
WARN  Deprecated config detected: "external_link" with a Boolean value is deprec                                      ated. See https://hexo.io/docs/configuration for more details.
INFO  Start processing
INFO  Files loaded in 449 ms
ERROR TypeError: E:\GitLab programs\hexostudy\themes\leo\layout\includes\layout.                                      pug:31
    29|           a(href='/')= config.title
    30|         div.layout-socialmedia.hide
  > 31|           each url,label in config.socialmedia
    32|             a(class='link-item main-link-item' title=label href=url)
    33|               i(class='iconfont icon-'+theme.social_icons[label])
    34|         div(class='responsive-bar', onclick='toggle(this)')= '\u2261'

Cannot read property 'length' of null
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:101:32)
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:120:4)
    at template (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-run                                      time\wrap.js:6:10), <anonymous>:205:275)
    at _View._compiled (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme                                      \view.js:136:50)
    at _View.render (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme\vi                                      ew.js:39:17)
    at E:\GitLab programs\hexostudy\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\GitLab programs\hexostudy\node_modules\bluebird\js\release                                      \util.js:16:23)
    at E:\GitLab programs\hexostudy\node_modules\bluebird\js\release\method.js:1                                      5:34
    at RouteStream._read (E:\GitLab programs\hexostudy\node_modules\hexo\lib\hex                                      o\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:469:10)
    at resume_ (_stream_readable.js:983:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\GitLab programs\\hexostudy\\themes\\leo\\layout\\includes\\layout.p                                      ug'
}
ERROR TypeError: E:\GitLab programs\hexostudy\themes\leo\layout\includes\layout.                                      pug:31
    29|           a(href='/')= config.title
    30|         div.layout-socialmedia.hide
  > 31|           each url,label in config.socialmedia
    32|             a(class='link-item main-link-item' title=label href=url)
    33|               i(class='iconfont icon-'+theme.social_icons[label])
    34|         div(class='responsive-bar', onclick='toggle(this)')= '\u2261'

Cannot read property 'length' of null
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:101:32)
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:120:4)
    at template (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-run                                      time\wrap.js:6:10), <anonymous>:209:275)
    at _View._compiled (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme                                      \view.js:136:50)
    at _View.render (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme\vi                                      ew.js:39:17)
    at E:\GitLab programs\hexostudy\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\GitLab programs\hexostudy\node_modules\bluebird\js\release                                      \util.js:16:23)
    at E:\GitLab programs\hexostudy\node_modules\bluebird\js\release\method.js:1                                      5:34
    at RouteStream._read (E:\GitLab programs\hexostudy\node_modules\hexo\lib\hex                                      o\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:469:10)
    at resume_ (_stream_readable.js:983:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\GitLab programs\\hexostudy\\themes\\leo\\layout\\includes\\layout.p                                      ug'
}
ERROR TypeError: E:\GitLab programs\hexostudy\themes\leo\layout\includes\layout.                                      pug:31
    29|           a(href='/')= config.title
    30|         div.layout-socialmedia.hide
  > 31|           each url,label in config.socialmedia
    32|             a(class='link-item main-link-item' title=label href=url)
    33|               i(class='iconfont icon-'+theme.social_icons[label])
    34|         div(class='responsive-bar', onclick='toggle(this)')= '\u2261'

Cannot read property 'length' of null
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:101:32)
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:120:4)
    at template (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-run                                      time\wrap.js:6:10), <anonymous>:235:275)
    at _View._compiled (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme                                      \view.js:136:50)
    at _View.render (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme\vi                                      ew.js:39:17)
    at E:\GitLab programs\hexostudy\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\GitLab programs\hexostudy\node_modules\bluebird\js\release                                      \util.js:16:23)
    at E:\GitLab programs\hexostudy\node_modules\bluebird\js\release\method.js:1                                      5:34
    at RouteStream._read (E:\GitLab programs\hexostudy\node_modules\hexo\lib\hex                                      o\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:469:10)
    at resume_ (_stream_readable.js:983:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\GitLab programs\\hexostudy\\themes\\leo\\layout\\includes\\layout.p                                      ug'
}
ERROR TypeError: E:\GitLab programs\hexostudy\themes\leo\layout\includes\layout.                                      pug:31
    29|           a(href='/')= config.title
    30|         div.layout-socialmedia.hide
  > 31|           each url,label in config.socialmedia
    32|             a(class='link-item main-link-item' title=label href=url)
    33|               i(class='iconfont icon-'+theme.social_icons[label])
    34|         div(class='responsive-bar', onclick='toggle(this)')= '\u2261'

Cannot read property 'length' of null
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:101:32)
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:120:4)
    at template (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-run                                      time\wrap.js:6:10), <anonymous>:235:275)
    at _View._compiled (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme                                      \view.js:136:50)
    at _View.render (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme\vi                                      ew.js:39:17)
    at E:\GitLab programs\hexostudy\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\GitLab programs\hexostudy\node_modules\bluebird\js\release                                      \util.js:16:23)
    at E:\GitLab programs\hexostudy\node_modules\bluebird\js\release\method.js:1                                      5:34
    at RouteStream._read (E:\GitLab programs\hexostudy\node_modules\hexo\lib\hex                                      o\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:469:10)
    at resume_ (_stream_readable.js:983:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\GitLab programs\\hexostudy\\themes\\leo\\layout\\includes\\layout.p                                      ug'
}
ERROR TypeError: E:\GitLab programs\hexostudy\themes\leo\layout\includes\layout.                                      pug:31
    29|           a(href='/')= config.title
    30|         div.layout-socialmedia.hide
  > 31|           each url,label in config.socialmedia
    32|             a(class='link-item main-link-item' title=label href=url)
    33|               i(class='iconfont icon-'+theme.social_icons[label])
    34|         div(class='responsive-bar', onclick='toggle(this)')= '\u2261'

Cannot read property 'length' of null
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:101:32)
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:120:4)
    at template (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-run                                      time\wrap.js:6:10), <anonymous>:235:275)
    at _View._compiled (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme                                      \view.js:136:50)
    at _View.render (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme\vi                                      ew.js:39:17)
    at E:\GitLab programs\hexostudy\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\GitLab programs\hexostudy\node_modules\bluebird\js\release                                      \util.js:16:23)
    at E:\GitLab programs\hexostudy\node_modules\bluebird\js\release\method.js:1                                      5:34
    at RouteStream._read (E:\GitLab programs\hexostudy\node_modules\hexo\lib\hex                                      o\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:469:10)
    at resume_ (_stream_readable.js:983:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\GitLab programs\\hexostudy\\themes\\leo\\layout\\includes\\layout.p                                      ug'
}
ERROR TypeError: E:\GitLab programs\hexostudy\themes\leo\layout\index.pug:24
    22|             a(href=url)= label
    23|       div.main-socialmedia
  > 24|         each url,label in config.socialmedia
    25|           a(class='link-item main-link-item' title=label href=url)
    26|             i(class='iconfont icon-'+theme.social_icons[label])
    27|       footer#bottom

Cannot read property 'length' of null
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:95:32)
    at eval (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-runtime                                      \wrap.js:6:10), <anonymous>:114:4)
    at template (eval at wrap (E:\GitLab programs\hexostudy\node_modules\pug-run                                      time\wrap.js:6:10), <anonymous>:169:72)
    at _View._compiled (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme                                      \view.js:136:50)
    at _View.render (E:\GitLab programs\hexostudy\node_modules\hexo\lib\theme\vi                                      ew.js:39:17)
    at E:\GitLab programs\hexostudy\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\GitLab programs\hexostudy\node_modules\bluebird\js\release                                      \util.js:16:23)
    at E:\GitLab programs\hexostudy\node_modules\bluebird\js\release\method.js:1                                      5:34
    at RouteStream._read (E:\GitLab programs\hexostudy\node_modules\hexo\lib\hex                                      o\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:469:10)
    at resume_ (_stream_readable.js:983:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\GitLab programs\\hexostudy\\themes\\leo\\layout\\index.pug'
}
INFO  Generated: index.html
INFO  Generated: about/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2021/index.html
INFO  Generated: archives/2021/01/index.html
INFO  Generated: favicon.ico
INFO  Generated: css/archive-smallscreen.css
INFO  Generated: css/layout-smallscreen.css
INFO  Generated: css/post.css
INFO  Generated: css/page.css
INFO  Generated: 2021/01/28/hello-world/index.html
INFO  Generated: css/index.css
INFO  Generated: css/archive.css
INFO  Generated: js/style.js
INFO  Generated: css/layout.css
INFO  Generated: css/style.css
INFO  Generated: image/bgi.jpg
INFO  17 files generated in 595 ms
```

**Comment by sandianyiyuan** [comment]
> Deprecated config detected: "external_link" with a Boolean value is deprec

根据`Deprecated config detected: "external_link" with a Boolean value is deprec`这个提示百度查到一个配置修改后可以生成了。[https://blog.csdn.net/qq_16232497/article/details/108292780](https://blog.csdn.net/qq_16232497/article/details/108292780)
